theme: jekyll-theme-minimal
title: Selective sips - cultural and bias trends in beer preferences across countries (by DataPilots)
description: Website showing the results of an analysis aiming at identifying external factors that shape beer preferences.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
