theme: jekyll-theme-minimal
title: Selective sips
description: Website showing the results of an analysis aiming at identifying external factors that shape beer preferences.
show_downloads: True
navigation:
  - title: Introduction
    url: /#introduction
  - title: Cultural influence on beer preferences
    url: /#Cultural_influence_on_beer_preferences
  - title: Location-related biases in ratings
    url: /#Location_related_biases_in_ratings  
  - title: Other biases
    url: /#Other_biases 
  - title: Conclusion
    url: /#conclusion